# ===============================
# SERVER
# ===============================
server.port=8081
spring.application.name=identity-service

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/identity_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info

# ===============================
# JWT CONFIG
# ===============================
security.jwt.issuer=${JWT_ISSUER:pdf-platform}
security.jwt.ttl-seconds=${JWT_TTL_SECONDS:86400}
security.jwt.private-key-pem=${JWT_PRIVATE_KEY_PEM:}
security.jwt.public-key-pem=${JWT_PUBLIC_KEY_PEM:}
security.jwt.private-key-path=private.pem
security.jwt.public-key-path=public.pem